# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import protos.embedding_pb2 as embedding__pb2


class ImageProcedureStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageToEmbedding = channel.unary_unary(
            '/ImageProcedure/ImageToEmbedding',
            request_serializer=embedding__pb2.B64Image.SerializeToString,
            response_deserializer=embedding__pb2.Embedding.FromString,
        )


class ImageProcedureServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageToEmbedding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcedureServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ImageToEmbedding': grpc.unary_unary_rpc_method_handler(
            servicer.ImageToEmbedding,
            request_deserializer=embedding__pb2.B64Image.FromString,
            response_serializer=embedding__pb2.Embedding.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'ImageProcedure', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ImageProcedure(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageToEmbedding(request,
                         target,
                         options=(),
                         channel_credentials=None,
                         call_credentials=None,
                         insecure=False,
                         compression=None,
                         wait_for_ready=None,
                         timeout=None,
                         metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageProcedure/ImageToEmbedding',
                                             embedding__pb2.B64Image.SerializeToString,
                                             embedding__pb2.Embedding.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
