# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\"\x1e\n\tEmbedding\x12\x11\n\tembedding\x18\x01 \x03(\x02\";\n\x08\x42\x36\x34Image\x12\x10\n\x08\x62\x36\x34image\x18\x01 \x01(\t\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x32=\n\x0eImageProcedure\x12+\n\x10ImageToEmbedding\x12\t.B64Image\x1a\n.Embedding\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMBEDDING._serialized_start=19
  _EMBEDDING._serialized_end=49
  _B64IMAGE._serialized_start=51
  _B64IMAGE._serialized_end=110
  _IMAGEPROCEDURE._serialized_start=112
  _IMAGEPROCEDURE._serialized_end=173
# @@protoc_insertion_point(module_scope)
